### ISSUE TITLE
Option to block forever

### ISSUE THREAD

**Issue by joesondow** [tveastman/secateur#12]
While the time-out idea is a nice option to have, there are situations where blocking someone and their followers forever would be more helpful. The current maximum block time seems to be 52 weeks (1 year). I would like the option of blocking an account and its followers for, let’s say, 100 years, or with no expiration. Whichever is easier to implement.

**Comment by tveastman** [comment]
I've never really been a fan of this idea. But you're not the only person who's asked for it, and there was never a *technical* reason to not have it (in fact, the unblock is more work anyway).

You can now choose 'forever' when you block people.

Thanks for your contribution! Take care!
